/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "onConnect": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L9C3",
    "exposed": false
  },
  "onDisconnect": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L18C3",
    "exposed": false
  },
  "authenticate": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L28C3",
    "exposed": false
  },
  "subscribe": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L37C3",
    "exposed": false
  },
  "unsubscribe": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L43C3",
    "exposed": false
  },
  "emitMessage": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L51C3",
    "exposed": false
  },
  "onMessage": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L60C3",
    "exposed": false
  },
  "progressiveEnhancementExample": {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3",
    "exposed": false
  }
})