/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', [
  {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3",
    "route": "/status/sse",
    "method": "get"
  },
  {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3",
    "route": "/status/http",
    "method": "get"
  }
])