/**
 * This file was generated by the @pikku/cli
 */
/* Import and register RPCs */
import { addFunction } from '@pikku/core'
import { authenticate } from '../../src/channel.functions.js'
import { emitMessage } from '../../src/channel.functions.js'
import { onConnect } from '../../src/channel.functions.js'
import { onDisconnect } from '../../src/channel.functions.js'
import { onMessage } from '../../src/channel.functions.js'
import { progressiveEnhancementExample } from '../../src/http-progressive-enhancement.functions.js'
import { subscribe } from '../../src/channel.functions.js'
import { unsubscribe } from '../../src/channel.functions.js'

addFunction('authenticate', { func: authenticate })
addFunction('emitMessage', { func: emitMessage })
addFunction('onConnect', { func: onConnect })
addFunction('onDisconnect', { func: onDisconnect })
addFunction('onMessage', { func: onMessage })
addFunction('progressiveEnhancementExample', { func: progressiveEnhancementExample })
addFunction('subscribe', { func: subscribe })
addFunction('unsubscribe', { func: unsubscribe })