/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "pikkuFn_src_channel_functions_ts_L9C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L9C3",
    "name": "onConnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "schemaName": "OnConnectInput",
    "inputs": [
      "OnConnectInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L18C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L18C3",
    "name": "onDisconnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "schemaName": null,
    "inputs": [],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L28C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L28C3",
    "name": "authenticate",
    "services": {
      "optimized": true,
      "services": [
        "userSession"
      ]
    },
    "schemaName": "AuthenticateInput",
    "inputs": [
      "AuthenticateInput"
    ],
    "outputs": [
      "AuthenticateOutput"
    ]
  },
  "pikkuFn_src_channel_functions_ts_L37C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L37C3",
    "name": "subscribe",
    "services": {
      "optimized": true,
      "services": [
        "eventHub",
        "channel"
      ]
    },
    "schemaName": "SubscribeInput",
    "inputs": [
      "SubscribeInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L43C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L43C3",
    "name": "unsubscribe",
    "services": {
      "optimized": true,
      "services": [
        "channel",
        "eventHub"
      ]
    },
    "schemaName": "UnsubscribeInput",
    "inputs": [
      "UnsubscribeInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_channel_functions_ts_L51C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L51C3",
    "name": "emitMessage",
    "services": {
      "optimized": true,
      "services": [
        "userSession",
        "eventHub",
        "channel"
      ]
    },
    "schemaName": "EmitMessageInput",
    "inputs": [
      "EmitMessageInput"
    ],
    "outputs": [
      "EmitMessageOutput"
    ]
  },
  "pikkuFn_src_channel_functions_ts_L60C3": {
    "pikkuFuncName": "pikkuFn_src_channel_functions_ts_L60C3",
    "name": "onMessage",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "schemaName": "OnMessageInput",
    "inputs": [
      "OnMessageInput"
    ],
    "outputs": [
      "OnMessageOutput"
    ]
  },
  "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3": {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3",
    "name": "progressiveEnhancementExample",
    "services": {
      "optimized": false,
      "services": []
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "ProgressiveEnhancementExampleOutput"
    ]
  }
})