/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "onConnect": {
    "pikkuFuncName": "onConnect",
    "name": "onConnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "inputSchemaName": "OnConnectInput",
    "outputSchemaName": null,
    "inputs": [
      "OnConnectInput"
    ],
    "outputs": [],
    "isDirectFunction": true
  },
  "onDisconnect": {
    "pikkuFuncName": "onDisconnect",
    "name": "onDisconnect",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "inputSchemaName": null,
    "outputSchemaName": null,
    "inputs": [],
    "outputs": [],
    "isDirectFunction": true
  },
  "authenticate": {
    "pikkuFuncName": "authenticate",
    "name": "authenticate",
    "services": {
      "optimized": true,
      "services": [
        "userSession"
      ]
    },
    "inputSchemaName": "AuthenticateInput",
    "outputSchemaName": "AuthenticateOutput",
    "inputs": [
      "AuthenticateInput"
    ],
    "outputs": [
      "AuthenticateOutput"
    ],
    "isDirectFunction": true
  },
  "subscribe": {
    "pikkuFuncName": "subscribe",
    "name": "subscribe",
    "services": {
      "optimized": true,
      "services": [
        "eventHub",
        "channel"
      ]
    },
    "inputSchemaName": "SubscribeInput",
    "outputSchemaName": null,
    "inputs": [
      "SubscribeInput"
    ],
    "outputs": [],
    "isDirectFunction": true
  },
  "unsubscribe": {
    "pikkuFuncName": "unsubscribe",
    "name": "unsubscribe",
    "services": {
      "optimized": true,
      "services": [
        "channel",
        "eventHub"
      ]
    },
    "inputSchemaName": "UnsubscribeInput",
    "outputSchemaName": null,
    "inputs": [
      "UnsubscribeInput"
    ],
    "outputs": [],
    "isDirectFunction": true
  },
  "emitMessage": {
    "pikkuFuncName": "emitMessage",
    "name": "emitMessage",
    "services": {
      "optimized": true,
      "services": [
        "userSession",
        "eventHub",
        "channel"
      ]
    },
    "inputSchemaName": "EmitMessageInput",
    "outputSchemaName": "EmitMessageOutput",
    "inputs": [
      "EmitMessageInput"
    ],
    "outputs": [
      "EmitMessageOutput"
    ],
    "isDirectFunction": true
  },
  "onMessage": {
    "pikkuFuncName": "onMessage",
    "name": "onMessage",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "channel"
      ]
    },
    "inputSchemaName": "OnMessageInput",
    "outputSchemaName": "OnMessageOutput",
    "inputs": [
      "OnMessageInput"
    ],
    "outputs": [
      "OnMessageOutput"
    ],
    "isDirectFunction": true
  },
  "progressiveEnhancementExample": {
    "pikkuFuncName": "progressiveEnhancementExample",
    "name": "progressiveEnhancementExample",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "ProgressiveEnhancementExampleOutput",
    "inputs": [],
    "outputs": [
      "ProgressiveEnhancementExampleOutput"
    ],
    "isDirectFunction": true
  }
})